# Generated by Django 6.0.6 on 2026-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price, UAH/MWh')),
                ('sales_volume', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sales volume, MW.h')),
                ('purchase_volume', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Purchase volume, MW.h')),
                ('declared_sales_volume', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Declared sales volume, MW.h')),
                ('declared_purchase_volume', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Declared purchase volume, MW.h')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DAM Market Data',
                'verbose_name_plural': 'DAM Market Data',
                'ordering': ['-date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
